unit q_cjjetj;

interface

uses Windows, SysUtils, Messages, Classes, Graphics, Controls,
  StdCtrls, ExtCtrls, Forms, Quickrpt, QRCtrls;

type
  Tqr_cjjetj = class(TQuickRep)
    TitleBand1: TQRBand;
    QRLabel2: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel6: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel17: TQRLabel;
    SummaryBand1: TQRBand;
    QRShape2: TQRShape;
    QRLabel24: TQRLabel;
    QRExpr3: TQRExpr;
    DetailBand1: TQRBand;
    QRShape1: TQRShape;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRExpr2: TQRExpr;
    QRDBText2: TQRDBText;
    QRDBText3: TQRDBText;
    fromtodate: TQRLabel;
    qr_datefrom: TQRLabel;
    QRLabel10: TQRLabel;
    qr_dateto: TQRLabel;
  private

  public

  end;

var
  qr_cjjetj: Tqr_cjjetj;

implementation

{$R *.DFM}

end.
