unit q_ypjetj;

interface

uses Windows, SysUtils, Messages, Classes, Graphics, Controls,
  StdCtrls, ExtCtrls, Forms, Quickrpt, QRCtrls;

type
  Tqr_ypjetj = class(TQuickRep)
    TitleBand1: TQRBand;
    QRShape2: TQRShape;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel6: TQRLabel;
    QRLabel15: TQRLabel;
    DetailBand1: TQRBand;
    QRShape1: TQRShape;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    QRDBText3: TQRDBText;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText7: TQRDBText;
    SummaryBand1: TQRBand;
    QRLabel16: TQRLabel;
    QRExpr1: TQRExpr;
    QRLabel17: TQRLabel;
    zbrq: TQRLabel;
    fromtodate: TQRLabel;
    qr_datefrom: TQRLabel;
    QRLabel10: TQRLabel;
    qr_dateto: TQRLabel;
    QRExpr2: TQRExpr;
    QRLabel7: TQRLabel;
    QRDBText6: TQRDBText;
  private

  public

  end;

var
  qr_ypjetj: Tqr_ypjetj;

implementation

{$R *.DFM}

end.
