unit r_zzycx;

interface

uses Windows, SysUtils, Messages, Classes, Graphics, Controls,
  StdCtrls, ExtCtrls, Forms, Quickrpt, QRCtrls;

type
  Trpt_zzycx = class(TQuickRep)
    TitleBand1: TQRBand;
    QRLabel1: TQRLabel;
    ColumnHeaderBand1: TQRBand;
    QRLabel2: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel6: TQRLabel;
    QRGroup1: TQRGroup;
    QRDBText1: TQRDBText;
    QRBand1: TQRBand;
    QRExpr2: TQRExpr;
    SummaryBand1: TQRBand;
    QRShape4: TQRShape;
    QRShape5: TQRShape;
    QRExpr1: TQRExpr;
    QRGroup2: TQRGroup;
    QRDBText6: TQRDBText;
    QRBand2: TQRBand;
    QRExpr3: TQRExpr;
    QRShape3: TQRShape;
    DetailBand1: TQRBand;
    QRDBText3: TQRDBText;
    QRDBText7: TQRDBText;
    QRShape8: TQRShape;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRShape9: TQRShape;
    QRLabel8: TQRLabel;
    QRLabel9: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel11: TQRLabel;
    QRDBText4: TQRDBText;
    QRShape6: TQRShape;
    QRLabel7: TQRLabel;
  private

  public

  end;

var
  rpt_zzycx: Trpt_zzycx;

implementation

{$R *.DFM}

end.
